name: simpro_revops
version: '1.0.0'
config-version: 2

profile: simpro_revops

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  simpro_revops:
    staging:
      +materialized: view
      +schema: staging
    mart:
      +materialized: table
      +schema: mart
